#!/usr/bin/env python3
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# Copyright by contributors to this project.
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
"""Generate crates/openjd-expr/src/functions/unicode_tables.rs from CPython.

The OpenJD expression language string classification functions (isdigit,
isalpha, isalnum, isspace, isupper, islower) are specified to match Python's
str methods of the same name. Rust's std char methods use different Unicode
properties (e.g. `char::is_alphabetic()` is the `Alphabetic` property, which
is a superset of Python's `L*` general categories), so we generate lookup
tables directly from the CPython runtime that defines the semantics.

Run with the CPython version whose Unicode tables the crate should pin to:

    python scripts/generate_unicode_tables.py

The output file is checked in; regenerate it when intentionally moving to a
newer Unicode version, and update the spec note in
specs/expr/function-library.md to match.

Table definitions (per CPython Objects/unicodectype.c semantics):
- DIGIT:   chr(cp).isdigit()   — Numeric_Type = Decimal or Digit
- ALPHA:   chr(cp).isalpha()   — general category Lu/Ll/Lt/Lm/Lo
- ALNUM:   chr(cp).isalnum()   — ALPHA or Numeric_Type != None
- SPACE:   chr(cp).isspace()   — Zs/Zl/Zp or bidirectional WS/B/S
- UPPER:   chr(cp).isupper()   — Uppercase property (Lu + Other_Uppercase)
- LOWER:   chr(cp).islower()   — Lowercase property (Ll + Other_Lowercase)
- CASED:   UPPER or LOWER or general category Lt

str.isupper()/str.islower() are not per-character predicates: they require at
least one cased character and that every cased character is upper/lowercase.
The CASED table supports that composition in Rust.
"""

import sys
import unicodedata
from datetime import date

OUT_PATH = "crates/openjd-expr/src/functions/unicode_tables.rs"

SURROGATE_RANGE = range(0xD800, 0xE000)


def build_ranges(predicate):
    """Return sorted inclusive (start, end) ranges of code points matching predicate."""
    ranges = []
    start = None
    for cp in range(0x110000):
        # Surrogates cannot exist in Rust `char` or in well-formed Python str
        # data; treat them as non-matching.
        matches = cp not in SURROGATE_RANGE and predicate(chr(cp))
        if matches and start is None:
            start = cp
        elif not matches and start is not None:
            ranges.append((start, cp - 1))
            start = None
    if start is not None:
        ranges.append((start, 0x10FFFF))
    return ranges


def is_cased(ch):
    return ch.isupper() or ch.islower() or unicodedata.category(ch) == "Lt"


TABLES = [
    ("DIGIT", "str.isdigit code points (Numeric_Type = Decimal or Digit).", lambda c: c.isdigit()),
    ("ALPHA", "str.isalpha code points (general category Lu/Ll/Lt/Lm/Lo).", lambda c: c.isalpha()),
    ("ALNUM", "str.isalnum code points (ALPHA or any Numeric_Type).", lambda c: c.isalnum()),
    ("SPACE", "str.isspace code points (Zs/Zl/Zp or bidi WS/B/S).", lambda c: c.isspace()),
    ("UPPER", "Uppercase code points (Lu + Other_Uppercase).", lambda c: c.isupper()),
    ("LOWER", "Lowercase code points (Ll + Other_Lowercase).", lambda c: c.islower()),
    ("CASED", "Cased code points (UPPER or LOWER or category Lt).", is_cased),
]


def verify(table, predicate):
    """Round-trip check: table membership must equal the CPython predicate."""
    idx = 0
    for cp in range(0x110000):
        while idx < len(table) and table[idx][1] < cp:
            idx += 1
        in_table = idx < len(table) and table[idx][0] <= cp
        expected = cp not in SURROGATE_RANGE and predicate(chr(cp))
        assert in_table == expected, f"table/CPython mismatch at U+{cp:04X}"


def main():
    lines = [
        "// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.",
        "// Copyright by contributors to this project.",
        "// SPDX-License-Identifier: (Apache-2.0 OR MIT)",
        "",
        "//! Unicode lookup tables for Python-parity string classification.",
        "//!",
        f"//! GENERATED by scripts/generate_unicode_tables.py on {date.today()} — do not edit.",
        f"//! Source: CPython {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}.",
        "//!",
        "//! See the script docstring for the definition of each table.",
        "",
        "/// The Unicode version these tables were generated from.",
        "#[allow(dead_code)]",
        f'pub const UNICODE_VERSION: &str = "{unicodedata.unidata_version}";',
        "",
        "/// True if `c` falls in one of `table`'s inclusive ranges.",
        "pub fn in_table(table: &[(u32, u32)], c: char) -> bool {",
        "    let cp = c as u32;",
        "    table",
        "        .binary_search_by(|&(start, end)| {",
        "            if end < cp {",
        "                std::cmp::Ordering::Less",
        "            } else if start > cp {",
        "                std::cmp::Ordering::Greater",
        "            } else {",
        "                std::cmp::Ordering::Equal",
        "            }",
        "        })",
        "        .is_ok()",
        "}",
    ]
    for name, doc, predicate in TABLES:
        ranges = build_ranges(predicate)
        verify(ranges, predicate)
        print(f"{name}: {len(ranges)} ranges, {sum(e - s + 1 for s, e in ranges)} code points")
        lines.append("")
        lines.append(f"/// {doc}")
        lines.append("#[rustfmt::skip]")
        lines.append(f"pub static {name}: &[(u32, u32)] = &[")
        row = []
        for s, e in ranges:
            row.append(f"({s:#x}, {e:#x})")
            if len(row) == 6:
                lines.append("    " + ", ".join(row) + ",")
                row = []
        if row:
            lines.append("    " + ", ".join(row) + ",")
        lines.append("];")
    lines.extend(
        [
            "",
            "#[cfg(test)]",
            "mod tests {",
            "    use super::*;",
            "",
            "    /// Every table must be sorted, non-overlapping, non-adjacent, and",
            "    /// free of surrogate code points — the invariants `in_table`'s",
            "    /// binary search and the generator's range-merging rely on.",
            "    #[test]",
            "    fn tables_are_well_formed() {",
            "        for table in [DIGIT, ALPHA, ALNUM, SPACE, UPPER, LOWER, CASED] {",
            "            let mut prev_end: Option<u32> = None;",
            "            for &(start, end) in table {",
            "                assert!(start <= end);",
            "                assert!(end <= 0x10FFFF);",
            "                assert!(!(start <= 0xDFFF && end >= 0xD800), \"surrogates in table\");",
            "                if let Some(p) = prev_end {",
            "                    // Adjacent ranges would indicate a generator bug.",
            "                    assert!(start > p + 1, \"unmerged ranges at {start:#x}\");",
            "                }",
            "                prev_end = Some(end);",
            "            }",
            "        }",
            "    }",
            "",
            "    /// Exhaustive: `in_table` must agree with a linear scan for every",
            "    /// code point, covering all range-boundary edge cases.",
            "    #[test]",
            "    fn binary_search_matches_linear_scan() {",
            "        for table in [DIGIT, SPACE, CASED] {",
            "            for cp in 0..=0x10FFFFu32 {",
            "                let Some(c) = char::from_u32(cp) else { continue };",
            "                let linear = table.iter().any(|&(s, e)| s <= cp && cp <= e);",
            "                assert_eq!(in_table(table, c), linear, \"U+{cp:04X}\");",
            "            }",
            "        }",
            "    }",
            "}",
        ]
    )
    lines.append("")
    with open(OUT_PATH, "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
